# Generated by Django 2.2.2 on 2019-09-09 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cdtTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=50, null=True)),
                ('sex', models.BooleanField(default=0)),
                ('age', models.PositiveIntegerField(max_length=4)),
                ('openId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdtTest.CdtTest')),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
