# Generated by Django 2.2.2 on 2019-09-09 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20190909_1448'),
        ('cdtTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdttest',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.Person'),
            preserve_default=False,
        ),
    ]
